name: Build macOS Executable

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files (Debugging)
        run: ls -la SearchPostInfo  # main.py があるか確認

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --name=InstagramExtractor SearchPostInfo/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: InstagramExtractor-mac
          path: dist/InstagramExtractor
